// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa_RoEMIFwHCUExApTcpsVt4OzWiQK1Cs',
    appId: '1:1017920310095:android:17da7c4eece27626acd33a',
    messagingSenderId: '1017920310095',
    projectId: 'hello-world-c2bdf',
    databaseURL: 'https://hello-world-c2bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hello-world-c2bdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxu7TvlxiB8CW5grZKLJuyeqKpsyVE6d4',
    appId: '1:1017920310095:ios:5635aa6444a958b3acd33a',
    messagingSenderId: '1017920310095',
    projectId: 'hello-world-c2bdf',
    databaseURL: 'https://hello-world-c2bdf-default-rtdb.firebaseio.com',
    storageBucket: 'hello-world-c2bdf.firebasestorage.app',
    iosBundleId: 'com.spiderwebarts.helloWorld3',
  );

}